name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  static:
    name: Static code checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --all -- --check

  build:
    name: Fedora tests
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:42
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: dnf install -y cargo rustfmt clang-devel llvm-devel openssl-devel gcc golang capnproto sqlite-devel
    - name: Build
      run: cargo build --verbose
    - name: Run Rust tests
      run: cargo test --verbose
    - name: Run Go tests
      run: make -C go check
